version: '3.7'

volumes:
  postgres-data:
    name: postgres-data
    driver: local

networks:
  cobefy:
    name: cobefy
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_cobefy

services:

  cobefy:
    image: vvvaaalll/cobefy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres

    networks:
      - cobefy
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  postgres:
    image: postgres:14.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 5s
    networks:
      - cobefy
    hostname: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@cobenco.hr
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

    networks:
      - cobefy

    depends_on:
      - postgres